[package]
name = "search6"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
tokio = { version = "1.26", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
ahash = "0.8"
tera = "1.18"
mee6 = "0.1"
axum = "0"
oauth2 = "4.3"
twilight-model = "0.15"
xpd-rank-card = "0.0.2"
base64 = "0.21.0"
